# -*- coding: utf-8 -*-
"""MdD_Sesión10_Antonio.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hz70AL0pUpNSdkShGQAUdCb7KFvLk-l2

# <font color = #009b7d> Minería de Datos </font>
## <font color = #009b7d> Sesión 10: Python - Cargas de datos y complejidad de datos</font>
### <font color = #009b7d>Prof: Vilchis García Juan Ignacio </font>
#### <font color = #009b7d>Alumno: Rodríguez Esquivel Luis Antonio </font>
#### <font color = #009b7d>Fecha: Miércoles 15 de octubre de 2025 </font>

## Definir Tarea de Machine Learning

  * La naturaleza de la tarea de Machine Learning (ML) se define primariamente por la existencia y el tipo de la variable objetivo (o variable de salida) en el dataset.

  * Dependiendo de si el dataset tiene una variable objetivo y de qué tipo es (numérica o categórica), se determina si el problema es de Aprendizaje Supervisado (Clasificación o Regresión) o Aprendizaje No Supervisado (Clustering, entre otros).

### A. Tareas de Aprendizaje Supervisado (Clasificación y Regresión)

Estas tareas requieren que el dataset esté etiquetado, es decir, que cada fila de entrada (variables predictoras, X) tenga un valor de salida conocido (variable objetivo, y).

  * A. Clasificación

    Variable Objetivo (y): Categórica o Discreta.

    Ejemplos de valores de y: "Sí/No", "Perro/Gato/Pájaro", "Clase A/Clase B", "Bajo/Medio/Alto".

    Pregunta Clave: ¿A qué categoría pertenece esta observación?

    Subtipos de Clasificación:

    * Clasificación Binaria: Solo dos posibles categorías de salida (ej. 0 o 1, True o False).

    * Clasificación Multiclase: Tres o más categorías de salida (ej. Tipo de flor, tipo de enfermedad).

  * B. Regresión

    Variable Objetivo (y): Numérica y Continua.

    Ejemplos de valores de y: 25.5, 150,000, 98.6 (valores que caen en un rango continuo).

    Pregunta Clave: ¿Cuál es el valor exacto de esta observación?

### B. Tareas de Aprendizaje No Supervisado (Clustering y otras)

Estas tareas se utilizan cuando el dataset no tiene una variable objetivo (y) pre-etiquetada. El objetivo es descubrir estructuras o patrones inherentes en los datos de entrada (X).

  * C. Clustering (Agrupamiento)

    Variable Objetivo (y): Inexistente. El dataset solo contiene variables de entrada (X).

    Pregunta Clave: ¿Cómo se agrupan las observaciones de forma natural?

    Propósito: Explorar la estructura de los datos para encontrar segmentos o grupos de observaciones similares (ej. Segmentación de clientes en marketing).

  * D. Reducción de Dimensionalidad
    
    Variable Objetivo (y): Inexistente.

    Propósito: Simplificar el dataset al reducir el número de variables de entrada (X) sin perder mucha información, facilitando el análisis o mejorando la velocidad de otros modelos de ML. (Ej. Principal Component Analysis - PCA).

###Tarea 1 : Clasificación
* Tipo de Aprendizaje: Supervisado

  * Característica Clave del Dataset: SÍ tiene una columna de salida etiquetada.

  * Tipo de Variable Objetivo (y): Categórica (discreta, finita, clases).

  * ¿Qué Predice/Resuelve?: Una etiqueta o categoría (ej. Fraude/No Fraude, A/B/C, Spam/No Spam)

### Tarea 2: Regresión

  * Tipo de Aprendizaje: Supervisado

  * Característica Clave del Dataset: SÍ tiene una columna de salida etiquetada.

  * Tipo de Variable Objetivo (y): Numérica (continua, infinita, valor).

  * ¿Qué Predice/Resuelve?: Un valor numérico continuo (ej. Precio de una casa, Temperatura, Ventas futuras).

### Tarea 3: Clustering (Agrupamiento)

  * Tipo de Aprendizaje: No Supervisado

  * Característica Clave del Dataset: NO tiene columna de salida pre-etiquetada.

  * Tipo de Variable Objetivo (y): Ninguna (solo variables de entrada X).

  * ¿Qué Predice/Resuelve?: Agrupaciones o patrones naturales dentro de los datos (ej. Segmentos de clientes).

### Tarea 4: Otros No Supervisados (Ej. Reducción de Dimensionalidad)

  * Tipo de Aprendizaje: No Supervisado

  * Característica Clave del Dataset: NO tiene columna de salida pre-etiquetada.

  * Tipo de Variable Objetivo (y): Ninguna.

  * ¿Qué Predice/Resuelve?: Reducción de dimensionalidad o detección de anomalías.

### Flujo de Decisión

Para determinar la tarea de ML, seguiremos este sencillo flujo:

1. ¿Hay una variable objetivo (y) en el dataset?

  * NO: → El problema es de Aprendizaje No Supervisado (probablemente Clustering o Reducción de Dimensionalidad, lo clasificaremos en OTRO).

  * SÍ: → El problema es de Aprendizaje Supervisado. Pasa al paso 2.

2. Si hay una variable objetivo (y), ¿de qué tipo es?

  * Categórica (Clases, Etiquetas): → Es un problema de Clasificación.

  * Númerica (Continua, Valores): → Es un problema de Regresión.

### EDA o Exploratory Data Analysis

Proceso crítico e iterativo de investigar un conjunto de datos para descubrir sus principales características, patrones, anomalías y relaciones.

Se realiza principalmente a través de métodos de resumen estadístico y técnicas de visualización gráfica.

Acuñado por el matemático estadounidense John W. Tukey, el EDA no se enfoca en la formulación de modelos predictivos finales, sino en el entendimiento profundo de los datos.

En una analogía profesional, el EDA es equivalente a la labor de un detective que llega a la escena de un crimen: su primer objetivo no es arrestar a un sospechoso, sino examinar toda la evidencia disponible, identificar pistas, entender el contexto y formular teorías sobre lo que ocurrió.

Un EDA sistemático generalmente involucra las siguientes etapas:

  * Revisar las primeras y últimas filas del conjunto de datos.

  * Determinar las dimensiones - Patrones y variables (número de filas y columnas).

  * Cuantificar y visualizar la distribución de valores perdidos.

  * Identificar los tipos de datos de cada columna.

  * Utilizar resúmenes estadísticos (media, mediana, desviación estándar, cuantiles) para las variables numéricas.

  * Identificar y, si es necesario, tratar registros duplicados.

## EDA - Iris Dataset
"""

#Dependences
import pandas as pd
import numpy as np

# Read csv
data = pd.read_csv("iris.csv")
data

# Display the first rows using .heads()
data.head(5)

# Display the last rows using .tail()
data.tail(5)

# Display random rows using .sample()
data.sample(5)

# Display the dimensions
data.shape

"""### 1. Valores perdidos:

Los valores perdidos (o missing values) son datos que no están disponibles para una observación o variable en particular dentro de un conjunto de datos.
"""

# Check the total number of missing items per column
data.isnull().sum()

# Check the total number of missing values
data.isnull().sum().sum()

# Visualize missing values
import seaborn as sns
sns.heatmap(data.isnull())

# Visualize missing values
import missingno as msno
msno.matrix(data)

"""### 2. Tipos de datos:

  * Numéricos:

    * Continuos: Edad, ingresos, temperatura.

    * Discretos: Número de hijos, cantidad de transacciones.

  * Categóricos:

    * Nominales: Ciudad de residencia, color favorito, estado civil.

    * Ordinales: Nivel de educación (primaria, secundaria, universidad),     clasificación de satisfacción (baja, media, alta).
  
  * Mezclados o Mixtos:

      Se refieren a la presencia de variables (columnas) con tipos de datos diferentes (generalmente numéricos y categóricos) dentro del mismo conjunto de datos (dataset).
"""

# Display attributes or characteristics

data.info()

# Data type
data.dtypes

# Columns o attributes names
data.columns

# Verify the sepal_length columns
data['sepal_length']

# Verify the petal_length column
data['petal_length']

# Get a statistical summary about the data
data.describe()

"""El banco de datos Iris tiene solo valores númericos continuos.

### 3. Cardinalidad de las clases (Desbalance de clases) (SOLO PARA LA TAREA: CLASIFICACIÓN)

El desbalance entre clases (o class imbalance) es un problema fundamental en Machine Learning (ML) y Ciencia de Datos (DS) que ocurre en los problemas de clasificación.

Se presenta cuando las categorías (clases) de la variable objetivo (la que queremos predecir) no están distribuidas uniformemente.
"""

# Verify unique classes
data['species'].unique()

# Visualize cardinality of classes or class imbalance
import seaborn as sns
sns.countplot(x = 'species', data = data)

# Verify cardinality of classes

data['species'].value_counts()

# Imbalanced ratio = Majority class cardinality / minority class cardinality <= 1.5 = balanced

print(f' IR = {50/50}')

"""El banco de datos iris tiene un IR = 1.0. Es un banco de datos balnceado."""

# Verify cardinality of versicolor

versicolor_class = data[data['species'] == 'versicolor']
versicolor_class

# Get a statistical summary about the versicolor class

versicolor_class.describe().round(2)

"""### 4. Outliers o valores atípicos

Un dato atípico u outlier es un punto de datos que difiere significativamente de otras observaciones. Es un valor que se encuentra a una distancia inusual del resto de los datos de un conjunto.

Método del Rango Intercuartílico (IQR)

Este método es robusto frente a otros outliers y se basa en los cuartiles de la distribución. Se utiliza frecuentemente para visualizar datos en un diagrama de caja (Box Plot) .

Un valor se considera un outlier si está:

  * Por debajo de: Q1 −1.5 × IQR

  * Por encima de: Q3 + 1.5 × IQR

Donde:

Q1 es el primer cuartil (percentil 25).

Q3 es el tercer cuartil (percentil 75).

IQR = Q3 − Q1.
"""

# Verify Outliers
import numpy as np
import pandas as pd

#attribute = 'sepal_length'
#attribute = 'sepal_width'
#attribute = 'petal_length'
attribute = 'petal_width'

# Quartiles
Q1 = data[attribute].quantile(0.25)
Q3 = data[attribute].quantile(0.75)
IQR = Q3 - Q1

# Limits
lower_limit = Q1 - 1.5 * IQR
upper_limit = Q3 + 1.5 * IQR

# Identifying outliers
outliers = data[(data[attribute] < lower_limit) | (data[attribute] > upper_limit)]
print(f"Outliers:{attribute}")
display(outliers)

num_outliers = len(outliers)
print(f"Total de Outliers encontrados: {num_outliers}")

"""Attribute -> Outliers
  * sepal_length -> 0
  * sepal_width  -> 4
  * petal_length -> 0
  * petal_width  -> 0
"""

# Visualize outliers
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Define the column we want to display
attribute = 'sepal_length'
sns.boxplot(y = data[attribute])
plt.show()

# Visualize outliers
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Define the column we want to display
attribute = 'sepal_width'
sns.boxplot(y = data[attribute])
plt.show()

# Visualize outliers
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Define the column we want to display
attribute = 'petal_length'
sns.boxplot(y = data[attribute])
plt.show()

# Visualize outliers
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Define the column we want to display
attribute = 'petal_width'
sns.boxplot(y = data[attribute])
plt.show()